FROM python:3.10-slim

WORKDIR /app

COPY main.py ./main.py
COPY shoes.db ./shoes.db
COPY shoes/ ./shoes/
COPY markers/ ./markers/
COPY requirements.txt ./requirements.txt

# Certificats SSL
COPY 192.168.0.27.pem /certs/cert.pem
COPY 192.168.0.27-key.pem /certs/key.pem

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--ssl-keyfile", "/certs/key.pem", "--ssl-certfile", "/certs/cert.pem"]
