services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./shoes:/app/shoes
      - ./markers:/app/markers
      - ./shoes.db:/app/shoes.db
      - ./main.py:/app/main.py
      - ./cache:/app/pip_cache
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Madrid
    networks:
      - shoe-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
    environment:
      - TZ=Europe/Madrid
    networks:
      - shoe-net

networks:
  shoe-net: